apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: web
          image: mycompany/web:latest
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
